query($id:ID!){
  receta(id:$id){
    id
    nombre
    duracion
    servicios
    imagen
    descripcion
    ingredientes
    pasos
    likes
    categoria{
      id
      nombre
      slug
    }
    autor{
      username
    }
  }
}
